apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: oficina-cadastro-migration-db
  namespace: oficina
spec:
  provider: aws
  parameters:
    region: "@AWS_REGION@"
    objects: |
      - objectName: "/oficina/cadastro/migration-db"
        objectType: "secretsmanager"
        jmesPath:
          - path: ConnectionString
            objectAlias: ConnectionStrings__OficinaCadastroDb
