apiVersion: v1
kind: ServiceAccount
metadata:
  name: cadastro-runtime
  namespace: oficina
  labels:
    app.kubernetes.io/name: oficina-cadastro
    app.kubernetes.io/component: runtime
  annotations: @RUNTIME_IRSA_ANNOTATION@
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cadastro-migrator
  namespace: oficina
  labels:
    app.kubernetes.io/name: oficina-cadastro
    app.kubernetes.io/component: migration
  annotations: @MIGRATION_IRSA_ANNOTATION@
